name: CI & CD

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: ./.github/scripts/lint.bash

      - name: Mirror
        env:
          AWS_SHA_ACCESS_KEY_ID: ${{ secrets.AWS_SHA_ACCESS_KEY_ID }}
          AWS_SHA_SECRET_ACCESS_KEY: ${{ secrets.AWS_SHA_SECRET_ACCESS_KEY }}
        run: ./.github/scripts/dev_mirror_sync.bash

      - name: Extract tag version from ref
        if: startsWith(github.ref, 'refs/tags/r')
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: is_release_tag check
        id: tag_check
        env:
          RELEASE_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: echo ::set-output name=IS_RELEASE_TAG::$(./.github/scripts/is_release_tag.bash $RELEASE_TAG && $? == 0)

      - run: echo ${{ steps.tag_check.outputs.IS_RELEASE_TAG }}

      - uses: BSFishy/pip-action@v1
        if: ${{ steps.tag_check.outputs.IS_RELEASE_TAG == 0 }}
        with:
          packages: awscli

      - name: Deploy
        if: ${{ steps.tag_check.outputs.IS_RELEASE_TAG == 0 }}
        run: ./.github/scripts/push.bash
